In [1]:
#1Create a 3*3*3 array with random values


import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(4, 4, 4)

print(random_array)


[[[0.30950592 0.85671903 0.58313456 0.36990389]
  [0.45596295 0.39137829 0.54267662 0.81892792]
  [0.96024612 0.0399215  0.79421589 0.64770846]
  [0.01261492 0.11011259 0.52179878 0.18336651]]

 [[0.88622561 0.89371735 0.32321444 0.97494136]
  [0.41814329 0.79965981 0.06231595 0.64988345]
  [0.15788203 0.20433393 0.64927886 0.4727946 ]
  [0.9987074  0.16048043 0.81822662 0.11143731]]

 [[0.89508185 0.38242613 0.18494386 0.94713214]
  [0.24379776 0.68548785 0.4150351  0.333836  ]
  [0.44211024 0.68890546 0.29635055 0.53781254]
  [0.43101568 0.76813014 0.75728183 0.45525455]]

 [[0.22898479 0.44136116 0.47310363 0.12639036]
  [0.54389233 0.73892643 0.8064739  0.75012646]
  [0.7479249  0.17401603 0.17111323 0.80141816]
  [0.38987808 0.20306478 0.16720363 0.2172595 ]]]


In [2]:
#2Create a 5*5 matrix with values 1,2,3,4 just below the diagonal.

import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill values 1, 2, 3, 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [4]:
#3Create a 8*8 matrix and fill it with a checkerboard pattern.

import numpy as np

# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with alternating 1s and 0s
checkerboard[1::2, ::2] = 1  # Rows 2, 4, 6
checkerboard[::2, 1::2] = 1  # Rows 1, 3, 5, 7

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#4Normalize a 5*5 random matrix.

import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean_value) / std_deviation

print("Original Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.28147783 0.3797668  0.98603251 0.88150025 0.48365553]
 [0.29390266 0.49964439 0.46425414 0.88708011 0.06182797]
 [0.89447969 0.1502944  0.30007307 0.65354424 0.12911675]
 [0.89696793 0.68559467 0.49387701 0.42591881 0.340416  ]
 [0.05042829 0.87643282 0.75357024 0.45091958 0.92594575]]

Normalized Matrix:
[[-0.85672358 -0.51771583  1.57335052  1.2128091  -0.15939405]
 [-0.81386917 -0.10424698 -0.22631123  1.23205457 -1.61431619]
 [ 1.2575764  -1.30918731 -0.79258686  0.4265678  -1.38223098]
 [ 1.26615855  0.53711268 -0.1241392  -0.35853332 -0.65344038]
 [-1.65363476  1.19533108  0.77156671 -0.27230333  1.36610575]]


In [7]:
#5 How to find common values between two arrays?

import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)


Common Values: [3 4 5]


In [8]:
#6How to get the dates of yesterday, today, and tomorrow?


import numpy as np
import datetime

# Get today's date
today = np.datetime64('today')

# Calculate yesterday and tomorrow
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


In [9]:
#7consider two random array A and B, check if they are equal.

import numpy as np

# Create two random arrays A and B (replace these with your actual arrays)
A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

# Check if A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are equal.


In [10]:
#8 Create random vector of size 10 and replace the maximum values by 0.


import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced:", random_vector)

Random vector with the maximum value replaced: [0.37905629 0.         0.18093074 0.90700708 0.29303054 0.08667346
 0.29116056 0.86464066 0.80801525 0.52570541]


In [11]:
#9How to print all the values of an array?


import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Option 1: Using a loop to print each element
for value in my_array:
    print(value)

# Option 2: Using the print function to display the whole array
print("All values in the array:", my_array)










1
2
3
4
5
All values in the array: [1 2 3 4 5]


In [13]:
#10Subtract the mean of each row of a matrix


import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix using broadcasting
result_matrix = matrix - row_means

print("Original matrix:\n", matrix)
print("Result matrix (mean subtracted from each row):\n", result_matrix)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Result matrix (mean subtracted from each row):
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [14]:
#11Consider a given vector, how to add 1 to each element indexed by a second vector


import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5])

# Second vector with indices where you want to add 1
indices_to_add_1 = np.array([1, 3, 3, 4])

# Create a new vector with 1 added at the specified indices
result_vector = given_vector.copy()  # Create a copy to avoid modifying the original
result_vector[indices_to_add_1] += 1

print("Given vector:", given_vector)
print("Indices to add 1:", indices_to_add_1)
print("Result vector:", result_vector)

Given vector: [1 2 3 4 5]
Indices to add 1: [1 3 3 4]
Result vector: [1 3 3 5 6]


In [15]:
#12How to get the diagonal of a dot product?

import numpy as np

# Create two sample matrices
matrix_A = np.array([[1, 2],
                     [3, 4]])

matrix_B = np.array([[5, 6],
                     [7, 8]])

# Calculate the dot product of the two matrices
dot_product = np.dot(matrix_A, matrix_B)

# Get the diagonal of the dot product
diagonal = np.diagonal(dot_product)

print("Dot Product:")
print(dot_product)

print("Diagonal of the Dot Product:")
print(diagonal)

Dot Product:
[[19 22]
 [43 50]]
Diagonal of the Dot Product:
[19 50]


In [16]:
#13How to find the most frequent value in an array?


import numpy as np

# Create a sample array
my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Use bincount to count occurrences of each value
counts = np.bincount(my_array)

# Find the index of the maximum count (i.e., the most frequent value)
most_frequent_value = np.argmax(counts)

print("Array:", my_array)
print("Most frequent value:", most_frequent_value)

Array: [1 2 2 3 3 3 4 4 4 4]
Most frequent value: 4


In [17]:
#14How to get the n largest values of an array.


import numpy as np

# Create a sample array
my_array = np.array([5, 2, 9, 1, 8, 3, 7, 4, 6])

# Specify the number of largest values you want
n = 3

# Use partition to get the n largest values
n_largest_values = np.partition(my_array, -n)[-n:]

print("Array:", my_array)
print(f"{n} Largest Values:", n_largest_values)

Array: [5 2 9 1 8 3 7 4 6]
3 Largest Values: [7 8 9]


In [21]:
#15How to create a record array from a regular array?


import numpy as np

# Create a regular NumPy array
regular_array = np.array([[1, "Alice", 25],
                          [2, "Bob", 30],
                          [3, "Charlie", 35]])

# Define data types for each field in the record array
# In this example, we have an integer ID, a string name, and an integer age
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create the record array
record_array = np.array(regular_array, dtype=dtype)

print("Regular Array:")
print(regular_array)

print("\nRecord Array:")
print(record_array)

ValueError: invalid literal for int() with base 10: 'Alice'

In [22]:
#16How to swap two rows of an array?

import numpy as np

# Create a sample 2D array
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Define the row indices you want to swap
row1_index = 0
row2_index = 2

# Swap the rows
my_array[[row1_index, row2_index]] = my_array[[row2_index, row1_index]]

print("Array with Rows Swapped:")
print(my_array)



Array with Rows Swapped:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [23]:
#17Write python code to reshape to the next dimenson of numpy array?


import numpy as np

# Given array
given_array = np.array([[23, 34, 121],
                        [23, 22, 67],
                        [686, 434, 123]])

# Reshape to the next higher dimension
reshaped_array = given_array.reshape(-1, given_array.shape[-1])

print("Original Array:")
print(given_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]


In [2]:
#15How to create a record array from a regular array?

import numpy as np

# Create a regular array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 28)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Create a record array from the regular array
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

print("Regular Array:")
print(regular_array)

print("\nRecord Array:")
print(record_array)

Regular Array:
[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 28)]

Record Array:
((1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 28))
